baseurl = "https://example.org/"
languageCode = "en-us"
title = "RW Awesome Static Site"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"

[params]
    site_author = "Ronnie Wong"
    site_description = "The awesome blog of John Doe."
    location = "Mississauga, ON"
    # Link custom assets relative to /static
    avatar = "img/Praying_Mantis_logo.png"
    header_background = "img/Crying_Wolf.jpg"
    header_title = "RW Engineering & Design"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "spf13"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "digitalcraftsman"
    gplus     = ""
